apiRules:
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Request\.IRequestBuilder$
      type: Interface  
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Request\.ICommandSender$
      type: Interface
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Request\.IRestClientFactory$
      type: Interface
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.CommandSender
      type: Field
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.RequestBuilder
      type: Field
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.Configuration
      type: Field
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.DeviceType
      type: Property
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.GetClientTransactionId$
      type: Method
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.ExecuteRequest
      type: Method
  - exclude:
      uidRegex: ^ES\.Ascom.Alpaca\.Client\.Devices\.DeviceBase\.ExecuteRequestAsync
      type: Method