using ES.Ascom.Alpaca.Devices;

namespace ES.Ascom.Alpaca.Responses
{
    /// <summary>
    /// Response that return the value as a <see cref="PierSide"/>
    /// </summary>
    public class PierSideResponse : CommandResponse, IValueResponse<PierSide>
    {
        private PierSideResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PierSideResponse" /> class with the specified <paramref name="value"/>
        /// </summary>
        /// <param name="value">The value to set in the object</param>
        /// <param name="clientTransactionId">The client transaction Id that has been sent by the client</param>
        /// <param name="serverTransactionId">Server transaction id generated by the server</param>
        public PierSideResponse(PierSide value, uint clientTransactionId = 0, uint serverTransactionId = 0) : base(clientTransactionId, serverTransactionId)
        {
            Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PierSideResponse" /> class with the specified <paramref name="errorNumber"/> and <paramref name="errorMessage"/>
        /// </summary>
        /// <param name="errorNumber">An error code in the <see cref="ES.Ascom.Alpaca.Exceptions.ErrorCodes"/> code range</param>
        /// <param name="errorMessage">The message that describes the error</param>
        /// <param name="clientTransactionId">The client transaction Id that has been sent by the client</param>
        /// <param name="serverTransactionId">Server transaction id generated by the server</param>
        public PierSideResponse(int errorNumber, string errorMessage, uint clientTransactionId = 0, uint serverTransactionId = 0) : 
            base(errorNumber, errorMessage, clientTransactionId, serverTransactionId)
        {
        }
        
        /// <summary>
        /// Pier side returned by the device
        /// </summary>
        public PierSide Value { get; set; }
    }
}